name: Fuzz regression

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "Cargo.lock"
      - "Cargo.toml"
      - "fuzz/**"
      - "src/**"
  schedule:
    - cron: "43 3 * * 4"

permissions:
  contents: read

concurrency:
  group: fuzz-${{ github.ref }}
  cancel-in-progress: true

jobs:
  libfuzzer:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: dtolnay/rust-toolchain@8641a17e25bf5b40c118d48fe0f81e8655731839 # nightly-2026-07-13
        with:
          toolchain: nightly-2026-07-13
          components: rustfmt, clippy
      - uses: taiki-e/install-action@c44f6b046f1c29ae5918b1e0bfdbb2f1813836fd # v2.84.1
        with:
          tool: cargo-fuzz@0.13.2
      - run: cargo fmt --manifest-path fuzz/Cargo.toml --check
      - run: cargo clippy --manifest-path fuzz/Cargo.toml --all-targets -- -D warnings
      - run: scripts/run-fuzz-regression.sh
